import type { TripDetail, TripSummary } from "@biketrips/domain";

export const storyTrips: TripDetail[] = [
  {
    id: "40000000-0000-4000-8000-000000000001",
    slug: "moscow-evening-gravel",
    title: "Вечерний gravel по паркам",
    cityId: "10000000-0000-4000-8000-000000000001",
    city: "Москва",
    startDateTime: "2026-07-04T18:30:00+03:00",
    distanceKm: 42,
    difficulty: "medium",
    pace: "steady",
    bikeType: "gravel",
    asphaltPercent: 60,
    unpavedPercent: 40,
    unpavedSurfaceDetails: ["hardpack", "gravel", "forest_trails"],
    dropPolicy: "no_drop",
    status: "published",
    capacity: 14,
    confirmedParticipants: 8,
    coverImage: "/img/Photo2.jpg",
    description:
      "Ровный вечерний маршрут через парки и спокойные набережные. Подойдет тем, кто уверенно держит 22-24 км/ч и хочет прокатиться без гонки.",
    startLocationName: "Парк Победы, главный вход",
    startLat: null,
    startLng: null,
    paceMin: 20,
    paceMax: 24,
    routeDescription: "Парк Победы - Фили - Крылатское - набережные - Парк Победы.",
    routeGpxFileName: null,
    routeGpxDownloadUrl: null,
    equipmentRequirements: "Шлем, запасная камера, свет передний и задний.",
    rules: "Едем группой, ждем на развилках, без резких перестроений.",
    registrationMode: "automatic",
    organizer: {
      id: "demo-organizer-1",
      userId: "demo-user-1",
      displayName: "RideMate Moscow",
      isVerified: true,
    },
    participants: [
      {
        id: "participant-1",
        status: "confirmed",
        userId: "user-1",
        name: "Алексей",
        telegramUsername: "aleksei",
        phone: null,
      },
      {
        id: "participant-2",
        status: "confirmed",
        userId: "user-2",
        name: "Марина",
        telegramUsername: "marina_ride",
        phone: null,
      },
    ],
    waitlist: [],
    updates: [
      {
        id: "update-1",
        title: "Старт без изменений",
        body: "Собираемся у главного входа, проверяем свет и выезжаем в 18:30.",
        createdAt: "2026-07-03T12:00:00+03:00",
      },
    ],
  },
  {
    id: "40000000-0000-4000-8000-000000000002",
    slug: "spb-ladoga-social",
    title: "Ладожский социальный круг",
    cityId: "10000000-0000-4000-8000-000000000002",
    city: "Санкт-Петербург",
    startDateTime: "2026-07-06T10:00:00+03:00",
    distanceKm: 68,
    difficulty: "easy",
    pace: "relaxed",
    bikeType: "hybrid",
    asphaltPercent: 90,
    unpavedPercent: 10,
    unpavedSurfaceDetails: ["hardpack"],
    dropPolicy: "no_drop",
    status: "published",
    capacity: 18,
    confirmedParticipants: 18,
    coverImage: "/img/Photo3.jpg",
    description:
      "Дневная поездка в разговорном темпе с остановкой на кофе. Хороший вариант для первой длинной групповой покатушки.",
    startLocationName: "Финляндский вокзал",
    startLat: null,
    startLng: null,
    paceMin: 16,
    paceMax: 20,
    routeDescription: "Городской старт, тихие шоссе, финиш у электрички.",
    routeGpxFileName: null,
    routeGpxDownloadUrl: null,
    equipmentRequirements: "Исправный велосипед, вода, перекус, свет.",
    rules: "No-drop формат: никто не остается один.",
    registrationMode: "manual",
    organizer: {
      id: "demo-organizer-2",
      userId: "demo-user-2",
      displayName: "Северный велоклуб",
      isVerified: false,
    },
    participants: [],
    waitlist: [
      {
        id: "wait-1",
        position: 1,
        userId: "user-19",
        name: "Илья",
        promotedAt: null,
      },
    ],
    updates: [],
  },
  {
    id: "40000000-0000-4000-8000-000000000003",
    slug: "kazan-training-loop",
    title: "Темповая тренировка за городом",
    cityId: "10000000-0000-4000-8000-000000000003",
    city: "Казань",
    startDateTime: "2026-07-09T07:30:00+03:00",
    distanceKm: 54,
    difficulty: "hard",
    pace: "training",
    bikeType: "road",
    asphaltPercent: 100,
    unpavedPercent: 0,
    unpavedSurfaceDetails: [],
    dropPolicy: "drop",
    status: "draft",
    capacity: 10,
    confirmedParticipants: 4,
    coverImage: "/img/Photo1.jpg",
    description: "Утренняя тренировка с ровными сменами и коротким разбором после финиша.",
    startLocationName: "Компрессорный, парковка",
    startLat: null,
    startLng: null,
    paceMin: 30,
    paceMax: 36,
    routeDescription: "Кольцо по загородным дорогам с двумя рабочими отрезками.",
    routeGpxFileName: null,
    routeGpxDownloadUrl: null,
    equipmentRequirements: "Шоссейный велосипед, шлем, запас воды.",
    rules: "Drop-формат, участники должны уверенно ехать в группе.",
    registrationMode: "manual",
    organizer: {
      id: "demo-organizer-1",
      userId: "demo-user-1",
      displayName: "RideMate Moscow",
      isVerified: true,
    },
    participants: [],
    waitlist: [],
    updates: [],
  },
];

export function toTripSummary(trip: TripDetail): TripSummary {
  const {
    description: _description,
    startLocationName: _startLocationName,
    startLat: _startLat,
    startLng: _startLng,
    paceMin: _paceMin,
    paceMax: _paceMax,
    routeDescription: _routeDescription,
    routeGpxFileName: _routeGpxFileName,
    routeGpxDownloadUrl: _routeGpxDownloadUrl,
    equipmentRequirements: _equipmentRequirements,
    rules: _rules,
    registrationMode: _registrationMode,
    organizer: _organizer,
    participants: _participants,
    waitlist: _waitlist,
    updates: _updates,
    ...summary
  } = trip;

  return summary;
}
